CREATE TABLE books(
   book_id INTEGER UNSIGNED PRIMARY AUTO_INCREMENT,
   author ,
   title VARCHAR(100) NOT NULL,
   year INTEGER UNSIGNED NOT NULL DEFAULT 1990,
   language VARCHAR(2) NOT NULL DEFAULT 'es' COMMENT 'ISO 639',
   cover_url VARCHAR(500),
   price DOUBLE(6,2) NOT NULL DEFAULT 10.0,
   sellabe TINYINT(1) DEFAULT 1,
   copies INTEGER NOT NULL 1,
   description TEXT
);